[ANCHOR-634] Bump Java SDK version to 0.43.0 (#1289)
### Description

This bumps the Java SDK version from 0.42.0 to 0.43.0. This is an
attempt to resolve an issue with the payment observer getting stuck on
unparsable payment operations.

Bumping the SDK version required bumping the Kotlin to 1.9 and `ktfmt`
versions, which is why the lines changed are so large.

### Context

```
19:54:54.694 ERROR - o.s.a.p.p.o.s.StellarPaymentObserver - stellar payment observer stream error:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "problem"
at com.google.gson.Gson.fromJson(Gson.java:1238)
at com.google.gson.Gson.fromJson(Gson.java:1137)
at com.google.gson.Gson.fromJson(Gson.java:1047)
at com.google.gson.Gson.fromJson(Gson.java:982)
at org.stellar.sdk.requests.SSEStream$StellarEventSourceListener.onEvent(SSEStream.java:257)
at 
```

### Testing

- `./gradlew test`

### Documentation

N/A

### Known limitations

N/A